### PR TITLE
MergeSort  hacktoberfest-accepted

### PR DESCRIPTION
**Pull request by BoaMos**
sort method only work for int types .
soon to cast

### CODE REVIEW

**Comment by BoaMos** [comment]
hacktoberfest-accepted

**Comment by BoaMos** [comment]
hacktoberfest-accepted

**Comment by Bijay555** [comment]
Mergesort.java is already there. Please PR those algorithm that are not there

**Comment by BoaMos** [comment]
if only the codes where arranged in languages 
it won't be difficult to see  if im duplicating

**Pull request closed without merging**
