### PR TITLE
Create sort_search.c

### PR DESCRIPTION
**Pull request by Pratyushraj2121**
I have uploaded my file which consists of the following codes:
1. Sorting: Selection Sort, Insertion Sort, Merge Sort, Quick Sort.
2. Searching: Linear Search, Binary Search (using merge sorting).
3. Trees: Postorder, Preorder and Inorder traversal.  Inorder traversal will also give you the sorted list.

Thank You!

### CODE REVIEW

**Comment by Bijay555** [comment]
@Pratyushraj2121 can you make all these separate file. Also the tree related algos should go to tree algorithm folder and sorting to sorting algorithm. So arrange it

**Review by Bijay555 — CHANGES_REQUESTED** [review]
can you make all these separate file. Also the tree related algos should go to tree algorithm folder and sorting to sorting algorithm. So arrange it

**Comment by Pratyushraj2121** [comment]
I made all the changes that were requested. Can you please look into it.

Thank You!

**Comment by Pratyushraj2121** [comment]
Sir,
As suggested to me, I made all separated files now. 
#126  Four Sorting techniques
#127  Sorting in Binary Tree

Please look into it and merge!

Thank You!

**Pull request merged**
